import turtle
mrpen = turtle.Turtle()
mrpen.goto (200,0)
mrpen.write (mrpen.position())
mrpen.goto(-200,0)
mrpen.write(mrpen.position())
mrpen.goto (0,0)
mrpen.goto (0,200)
mrpen.write (mrpen.position())
mrpen.goto(0,-200)
mrpen.write(mrpen.position())
turtle.done()
